#!/bin/bash

if [ "$EMAIL" = "" ]
then
  echo "Please set EMAIL"
  exit 1
fi

if [ "$#" -lt 1 ]; then
  echo "Please specify at least one branch name"
  exit 1
fi

if [ "$SLEEP_INTERVAL" = "" ]
then
  SLEEP_INTERVAL="30s"
fi

repository_name=$(basename `git rev-parse --show-toplevel`)
working_folder="/tmp/$repository_name"
mkdir -p "$working_folder"

while [ 1 ]; do
  for branch in $@
  do
    log_file="$working_folder/$branch.log"
    gems_file="$working_folder/$branch_gems.log"
    # -d Remove untracked directories in addition to untracked files.
    git clean -d --force
    # in case this is the first time we're seeing this branch
    # FIXME: this is going to spit out a "fatal" warning if branch already tracked
    # -t, --track When creating a new branch, set up "upstream" configuration.
    git checkout --track origin/$branch
    git checkout $branch
    git fetch origin
    git ls-remote . | grep "heads/$branch$" | awk '{print $1}' > $working_folder/$branch-heads.hash
    git ls-remote . | grep "origin/$branch$" | awk '{print $1}' > $working_folder/$branch-origin.hash
    DIFF=`diff $working_folder/$branch-heads.hash $working_folder/$branch-origin.hash`
    if [ "" != "$DIFF" ]; then
      comment=`git log --oneline -1`
      # --hard Any changes to tracked files in the working tree discarded.
      git reset --hard origin/$branch > $log_file 2>&1
      bundle install > $gems_file 2>&1
      RAILS_ENV=test bundle exec rake db:migrate --trace >> $log_file 2>&1
      # gem 'minitest-profile' # required for --profile
      TESTOPTS='--profile' RAILS_ENV=test bundle exec rake test --verbose >> $log_file 2>&1
      # append the bundle install output AFTER the test data
      cat $gems_file >> $log_file 2>&1
      # why do we do this twice? to note anything that was "dirtied" into the log
      git reset --hard >> $log_file 2>&1
      ERR=`egrep '(Failure|Error):$' $log_file | wc -l`
      headline="$ERR tests failed for $repository_name $branch $comment"
      cat $log_file | perl -pe 's/\x1b\[[0-9;]*[mG]//g' | mail -s "$headline" $EMAIL
      if [ -z "$SLACKBOT_URL" ]; then
        echo "Please set SLACKBOT_URL so the Slack channel can be notified."
      else
        curl -X POST --data-urlencode "payload={\"channel\": \"#general\", \"username\": \"CI\", \"text\": \"$headline\", \"icon_emoji\": \":warning:\"}" "https://hooks.slack.com/services/$SLACKBOT_URL"
      fi
      rm log/test.log
    else
      echo NO CHANGES YET
    fi
    sleep "$SLEEP_INTERVAL"
  done
done
