#!/bin/bash

if [ "$EMAIL" = "" ]
then
  echo "Please set EMAIL"
  exit 1
fi

if [ "$#" -lt 1 ]; then
  echo "Please specify at least one branch name"
  exit 1
fi

if [ "$SLEEP_INTERVAL" = "" ]
then
  SLEEP_INTERVAL="9s"
fi

repository_name=$(basename `git rev-parse --show-toplevel`)
working_folder="/tmp/$repository_name"
mkdir -p "$working_folder"

while [ 1 ]; do
  for branch in $@
  do
    log_file="$working_folder/$branch.log"
    # -d Remove untracked directories in addition to untracked files.
    git clean -d --force
    # in case this is the first time we're seeing this branch
    # FIXME: this is going to spit out a "fatal" warning if branch already tracked
    # -t, --track When creating a new branch, set up "upstream" configuration.
    git checkout --track origin/$branch
    git checkout $branch
    git fetch origin
    git ls-remote . | grep "heads/$branch$" | awk '{print $1}' > $working_folder/$branch-heads.hash
    git ls-remote . | grep "origin/$branch$" | awk '{print $1}' > $working_folder/$branch-origin.hash
    DIFF=`diff $working_folder/$branch-heads.hash $working_folder/$branch-origin.hash`
    if [ "" != "$DIFF" ]; then
      # --hard Any changes to tracked files in the working tree discarded.
      git reset --hard origin/$branch > $log_file 2>&1
      bundle install >> $log_file 2>&1
      RAILS_ENV=test bundle exec rake db:migrate --trace >> $log_file 2>&1
      RAILS_ENV=test bundle exec rake test --verbose >> $log_file 2>&1
      # why do we do this twice? to note anything that was "dirtied" into the log
      git reset --hard >> $log_file 2>&1
      ERR=`egrep "Failure|\) Error:" $log_file | wc -l`
      cat $log_file | mail -s "$ERR tests failed for $repository_name $branch" $EMAIL
    else
      echo NO CHANGES YET
    fi
    sleep "$SLEEP_INTERVAL"
  done
done

